### ISSUE TITLE
Composer 2

### ISSUE THREAD

**Issue by j3j5** [edbizarro/gitlab-ci-pipeline-php#106]
Now that Composer 2 [has been released](https://blog.packagist.com/composer-2-0-is-now-available/) I was wondering what you think is the best approach to make it available on the image. 
Not sure if it makes sense to have both versions available for a while or if it'd be better to include version 2 directly since they are *mostly* compatible. An advantage is that we can remove prestissimo from the dependencies, for the rest, I've been testing it on the image and there's nothing else that seems to be causing issues.

I guess there will be people for which there may be some incompatibilities but if they've been using an up-to-date version of this image they probably have been getting warnings about it for a while.

What do you think? I can help create the PR with whatever approach you think is best.

Cheers!

**Comment by romainnorberg** [comment]
Hello @j3j5 

Temporarily, on an existing project, we are testing the following solution:

```yml
project:
  services:
    - mariadb:10.3
  image: edbizarro/gitlab-ci-pipeline-php:7.4-alpine
  script:
    - composer -V # Composer version 1.10.15 2020-10-13 15:59:09
    - sudo composer self-update --2 
    - composer -V 
    # The "hirak/prestissimo" plugin (installed globally) was skipped because it requires a Plugin API version ("^1.0.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option. 
    # Composer version 2.0.3 2020-10-28 15:50:55
```

I think it would be good to be able to switch from V1 to V2 and vice-versa.
