### ISSUE TITLE
PackageManifest.php Undefined index: name

### ISSUE THREAD

**Issue by herreralv-dev** [edbizarro/gitlab-ci-pipeline-php#119]
Good Day!

We are having issues after the update of Composer 2 release. It works fine the last few days, but when our developers started to commit and the pipeline starts.

Here's our gitlab-ci.yml:

```
image: edbizarro/gitlab-ci-pipeline-php:7.3-alpine

stages:
  - test
  - deploy


# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
  - postgres:12.3
  - redis:latest

variables:
  POSTGRES_DB: "core"
  POSTGRES_USER: "root"
  POSTGRES_PASSWORD: "secret"
  POSTGRES_HOST: "postgres"
  REDIS_PORT: 6379

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
# cache:
#   paths:
#    - vendor/
#    - node_modules/

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:
  # Install Composer and project dependencies.
  - composer install --prefer-dist --no-ansi --no-interaction --no-progress
  
  # Copy over testing configuration.
  # Don't forget to set the database config in .env.testing correctly
  # DB_HOST=mysql
  # DB_DATABASE=project_name
  # DB_USERNAME=root
  # DB_PASSWORD=secret
  - cp .env.testing .env

  # Generate an application key. Re-cache.
  - php artisan key:generate
  # - php artisan cache:clear -> not available in Laravel Lumen
  - php artisan optimize

  # Run database migrations.
  - php artisan migrate

  # Run the Laravel Passport table migrations.
  - php artisan passport:install --force

  # Run database seed.
  - php artisan db:seed

test:
  tags:
    - docker
  script:
    # run laravel tests
    - ./vendor/phpunit/phpunit/phpunit -v --coverage-text --colors=never --stderr

    # Run PHP Code Sniffer.
    - php vendor/bin/phpcs

deploy:
  stage: deploy
  image: edbizarro/gitlab-ci-pipeline-php:7.3-alpine
  script:
    - echo "Deployment handled by Laravel Forge!"
  only:
    - master
  when: on_success

```
![image](https://user-images.githubusercontent.com/31556634/106983553-0e2a9780-67a1-11eb-8eef-3e9ade957c65.png)

Looking forward to the resolution for this.

Thank you so much and have a good day!
