### ISSUE TITLE
pcntl extension not installed/enabled

### ISSUE THREAD

**Issue by simondotwhite** [edbizarro/gitlab-ci-pipeline-php#26]
Hi,

Today I've been getting errors saying the 'pcntl' extension is not installed/enabled. 

```
$ composer install --no-scripts  --prefer-dist > /dev/null
  Problem 1
    - laravel/horizon v1.1.0 requires ext-pcntl * -> the requested PHP extension pcntl is missing from your system.
    - laravel/horizon v1.1.0 requires ext-pcntl * -> the requested PHP extension pcntl is missing from your system.
    - Installation request for laravel/horizon v1.1.0 -> satisfiable by laravel/horizon[v1.1.0].
```

I've run php --ini within the Gitlab job shell file to figure out what's there. 

```
$ php --ini
Configuration File (php.ini) Path: /usr/local/etc/php
Loaded Configuration File:         (none)
Scan for additional .ini files in: /usr/local/etc/php/conf.d
Additional .ini files parsed:      /usr/local/etc/php/conf.d/apcu-recommended.ini,
/usr/local/etc/php/conf.d/docker-php-ext-apcu.ini,
/usr/local/etc/php/conf.d/docker-php-ext-bcmath.ini,
/usr/local/etc/php/conf.d/docker-php-ext-bz2.ini,
/usr/local/etc/php/conf.d/docker-php-ext-calendar.ini,
/usr/local/etc/php/conf.d/docker-php-ext-gd.ini,
/usr/local/etc/php/conf.d/docker-php-ext-imap.ini,
/usr/local/etc/php/conf.d/docker-php-ext-intl.ini,
/usr/local/etc/php/conf.d/docker-php-ext-ldap.ini,
/usr/local/etc/php/conf.d/docker-php-ext-mcrypt.ini,
/usr/local/etc/php/conf.d/docker-php-ext-memcached.ini,
/usr/local/etc/php/conf.d/docker-php-ext-mongodb.ini,
/usr/local/etc/php/conf.d/docker-php-ext-mysqli.ini,
/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini,
/usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini,
/usr/local/etc/php/conf.d/docker-php-ext-pdo_pgsql.ini,
/usr/local/etc/php/conf.d/docker-php-ext-pgsql.ini,
/usr/local/etc/php/conf.d/docker-php-ext-redis.ini,
/usr/local/etc/php/conf.d/docker-php-ext-soap.ini,
/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini,
/usr/local/etc/php/conf.d/docker-php-ext-zip.ini,
/usr/local/etc/php/conf.d/opcache-recommended.ini,
/usr/local/etc/php/conf.d/zz-conf.ini
```

The gitlab-ci.yml file looks like 

```
stages:
- standards
- tests

cache:
  key: $CI_BUILD_REF_NAME # changed to $CI_COMMIT_REF_NAME in Gitlab 9.x
  paths:
    - vendor
    - node_modules
    - public
    - .yarn

image: edbizarro/gitlab-ci-pipeline-php:7.1

before_script:
  - composer self-update
  - composer install --no-scripts  --prefer-dist > /dev/null
  - cp .env.example .env
  - php artisan key:generate

codestandards_job:
  stage: standards
  script:
    - ./vendor/bin/phpcs --colors --standard=PSR2 --file-list=phpcs.filelist

tests_job:
  stage: tests
  image: edbizarro/gitlab-ci-pipeline-php:7.1-alpine
  script:
    - ./vendor/bin/phpunit
```

Any help is appreciated.
