### ISSUE TITLE
How to use PHP Code Sniffer

### ISSUE THREAD

**Issue by molerat619** [edbizarro/gitlab-ci-pipeline-php#42]
Hey there,

thanks for this great package. I was fighting with the .yml files for days and yours just worked.

How can I use PHP Code Sniffer with this? I have the following configuration, but it won't work.

```
# Variables
variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: homestead
  MYSQL_PASSWORD: secret
  MYSQL_DATABASE: homestead
  DB_HOST: mysql

stages:
  - syntax
  - tests

phpcs:
  stage: syntax
  script:
    - ./vendor/bin/phpcs --error-severity=1 --warning-severity=8 --extensions=php

test:
  stage: test
  services:
    - mysql:5.7
  image: edbizarro/gitlab-ci-pipeline-php:7.2-alpine
  script:
    - yarn
    - cp .env.example .env
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    - php artisan key:generate
    - php artisan migrate:refresh --seed
    - ./vendor/phpunit/phpunit/phpunit -v --coverage-text --colors=never --stderr
```

But of course I get `/bin/bash: line 69: ./vendor/bin/phpcs: No such file or directory`.
