### ISSUE TITLE
[deploy] laravel envoy

### ISSUE THREAD

**Issue by pherum** [edbizarro/gitlab-ci-pipeline-php#45]
Please, add `laravel/envoy` in your `Dockerfile` for easy deploing

```
$ composer global require laravel/envoy
```

**Comment by edbizarro** [comment]
hi @PheRum 

such tools like envoy, deployer etc can be easily added in the pipeline task config like

```yaml
deploy:
  stage: deploy
  image: edbizarro/gitlab-ci-pipeline-php:7.2-alpine
  script:
    - composer require laravel/envoy
    - ./vendor/bin/envoy run task
  only:
    - master
  when: on_success
```
