### ISSUE TITLE
Passport install key cause "Segmentation fault"

### ISSUE THREAD

**Issue by pfaffenrodt** [edbizarro/gitlab-ci-pipeline-php#46]
In our Project we use Laravel Passport.
And passport require a generated key and this cause a segmentation fault.

```console
$ php artisan passport:keys
Encryption keys generated successfully.
/bin/bash: line 76:   510 Segmentation fault      (core dumped) php artisan passport:keys
```

Interesting part is that the command already sending "Encryption keys generated successfully.".
So is the simple output the cause of the seg.fault?

```php

 public function handle(RSA $rsa)
    {
        $keys = $rsa->createKey(4096);

        list($publicKey, $privateKey) = [
            Passport::keyPath('oauth-public.key'),
            Passport::keyPath('oauth-private.key'),
        ];

        if ((file_exists($publicKey) || file_exists($privateKey)) && ! $this->option('force')) {
            return $this->error('Encryption keys already exist. Use the --force option to overwrite them.');
        }

        file_put_contents($publicKey, array_get($keys, 'publickey'));
        file_put_contents($privateKey, array_get($keys, 'privatekey'));

        $this->info('Encryption keys generated successfully.');
    }
```

**Comment by edbizarro** [comment]
Hi @pfaffenrodt, please share your gitlab ci config and what image tag are u using?

**Comment by pfaffenrodt** [comment]
Hi @edbizarro

```yaml
image: edbizarro/gitlab-ci-pipeline-php:7.1-alpine

services:
- mysql:5.6

test:
    script:
        - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
        - php artisan key:generate
        - php artisan passport:keys
        - vendor/bin/phpunit -v --colors=never --stderr
```
