### ISSUE TITLE
Composer Permission denied problem

### ISSUE THREAD

**Issue by clavat** [edbizarro/gitlab-ci-pipeline-php#54]
Hello,

I get permission denied when I try to composer install

> Running` with gitlab-runner 11.7.0 (8bb608ff)
>   on docker-runner _2Cyso3z
> Using Docker executor with image edbizarro/gitlab-ci-pipeline-php:7.3 ...
> Pulling docker image edbizarro/gitlab-ci-pipeline-php:7.3 ...
> Using docker image sha256:e93124288ec669f2770c9844137887eeb6b5652698e7b48975581fc625387e52 for edbizarro/gitlab-ci-pipeline-php:7.3 ...
> Running on runner-_2Cyso3z-project-6-concurrent-0 via SERVER...
> Fetching changes...
> Removing public/bundles/
> Removing var/
> Removing vendor/
> HEAD is now at 29575a5 test gitlab
> From https://git.repo
> Checking out ec6949e3 as test gitlab...
> Skipping Git submodules setup
> Checking cache for default...
> No URL provided, cache will be not downloaded from shared cache server. Instead a local version of cache will be extracted. 
> Successfully extracted cache
> $ composer install --prefer-dist --no-ansi --no-interaction --no-progress
> Loading composer repositories with package information
> Installing dependencies (including require-dev) from lock file
> Nothing to install or update
> 
>                                                                                                                            
>   [ErrorException]                                                                                                         
>   file_put_contents(/builds/vendor/composer/installed.json): failed to open stream: Permission denied  
>                                                                                                                            
> 
> install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...
> 
> ERROR: Job failed: exit code 1

Here is my gitlab-ci.yml
```yaml
image: edbizarro/gitlab-ci-pipeline-php:7.3

before_script:
  - composer install --prefer-dist --no-ansi --no-interaction --no-progress
  - yarn install

stages:
  - build

cache:
  paths:
  - vendor/

build:
  stage: build
  artifacts:
    paths:
      - build/
  script:
    - mkdir build/
    - cp -r bin config public src templates vendor composer.* .env.dist build/
  only:
    - test_gitlab_ci
````

**Comment by edbizarro** [comment]
Weird, try clearing the pipeline cache, there's a button on the pipeline UI for this

**Comment by clavat** [comment]
I removed the part `cache` and now it works...

```yaml
cache:
  paths:
  - vendor/
```
So I don't know if its really a bug or not ?
