### ISSUE TITLE
Cannot find Chrome binary

### ISSUE THREAD

**Issue by slavarazum** [edbizarro/gitlab-ci-pipeline-php#58]
This error appears every during every test running:

```bash
Facebook\WebDriver\Exception\UnknownServerException: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.19.23-coreos-r1 x86_64)
```

My CI configuration:

```yml
dusk:
  stage: testing
  services:
    - mysql:5.7
    - redis:latest
  image: edbizarro/gitlab-ci-pipeline-php:7.3-chromium
  dependencies:
    - build-assets
    - publish-assets
    - composer
    - db-seeding
  script:
    - php -v
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    - php artisan serve &
    - ./vendor/laravel/dusk/bin/chromedriver-linux --port=9515 &
    - sleep 5
    - php artisan dusk --colors --exclude-group problem-testcase
  artifacts:
    paths:
      - ./storage/logs # for debugging
      - ./tests/Browser/screenshots # for Dusk screenshots
      - ./tests/Browser/console # for Dusk console
    expire_in: 1 days
    when: always
```

But before the error I see in output that chrome driver successfully started:

```bash
Starting ChromeDriver 2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5) on port 9515
Only local connections are allowed.
```
