### ISSUE TITLE
Package 'mysql-client' has no installation candidate on 7.2

### ISSUE THREAD

**Issue by NavyCoat** [edbizarro/gitlab-ci-pipeline-php#64]
I'm using gitlab CI with this config:
```
image: edbizarro/gitlab-ci-pipeline-php:7.2

cache:
  paths:
  - vendor/

variables:
  COMPOSER_DISABLE_XDEBUG_WARN: "1"
  COMPOSER_ALLOW_SUPERUSER: "1"
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: user
  MYSQL_PASSWORD: password
  MYSQL_DATABASE: foo_dev
  DB_HOST: mysql
  APP_ENV: test

services:
    - mysql:5.7
```

While giltab starts pipeline i receive this error: 

```
$ sudo apt-get update -q && sudo apt-get install -qqy --no-install-recommends mysql-client
Get:1 http://security-cdn.debian.org/debian-security buster/updates InRelease [39.1 kB]
Get:3 https://deb.nodesource.com/node_12.x buster InRelease [4584 B]
Get:2 http://cdn-fastly.deb.debian.org/debian buster InRelease [118 kB]
Get:4 http://cdn-fastly.deb.debian.org/debian buster-updates InRelease [46.8 kB]
Get:5 http://security-cdn.debian.org/debian-security buster/updates/main amd64 Packages [50.7 kB]
Get:6 http://cdn-fastly.deb.debian.org/debian buster/main amd64 Packages [7897 kB]
Get:7 https://deb.nodesource.com/node_12.x buster/main amd64 Packages [764 B]
Fetched 8157 kB in 2s (3784 kB/s)
Reading package lists...
E: Package 'mysql-client' has no installation candidate
```

Last successful build 21hours ago.
