### ISSUE TITLE
/bin/bash: line 97: ./vendor/phpunit/phpunit/phpunit: No such file or directory

### ISSUE THREAD

**Issue by abkrim** [edbizarro/gitlab-ci-pipeline-php#67]
Today I get this error on mi pipelines in stage testing

```bash
Downloading artifacts from coordinator... ok        id=1173 responseStatus=200 OK token=EshE9PoL
$ php -v
PHP 7.3.9 (cli) (built: Sep  3 2019 05:30:13) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.9, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.8.0beta2, Copyright (c) 2002-2019, by Derick Rethans
$ sudo cp /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.bak
$ echo "" | sudo tee /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

$ ./vendor/phpunit/phpunit/phpunit --version
/bin/bash: line 97: ./vendor/phpunit/phpunit/phpunit: No such file or directory
```

I've tried with:

- image: edbizarro/gitlab-ci-pipeline-php:7.3-alpine
- image: edbizarro/gitlab-ci-pipeline-php:7.3
- image: edbizarro/gitlab-ci-pipeline-php:7.2

Yesterday Dock runners work perfectly.

.gitlab-ci,.yaml

```
stages:
  - preparation
  - building
  - testing
  - security

variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: albarid_ci
  MYSQL_PASSWORD: albarid_secret
  MYSQL_DATABASE: albarid_ci
  DB_HOST: mysql

cache:
  key: $CI_BUILD_REF_NAME

composer:
  stage: preparation
  services:
    - {name: 'abkrim/mysql8_legacy_password:latest', alias: 'mysql'}
#    - mysql:latest
  image: edbizarro/gitlab-ci-pipeline-php:7.2
  script:
    - php -v
    - echo "{\"http-basic\":{\"nova.laravel.com\":{\"username\":\"${NOVA_USERNAME}\",\"password\":\"${NOVA_PASSWORD}\"}}}" > ~/.composer/auth.json
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.example .env
    - php artisan key:generate
  artifacts:
    paths:
      - vendor/
      - .env
    expire_in: 5 days
    when: always
  cache:
    paths:
      - vendor/

yarn:
  stage: preparation
  image: edbizarro/gitlab-ci-pipeline-php:7.2
  script:
    - yarn --version
    - yarn install --pure-lockfile
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 days
    when: always
  cache:
    paths:
      - node_modules/

build-assets:
  stage: building
  image: edbizarro/gitlab-ci-pipeline-php:7.2
  dependencies:
    - composer
    - yarn
  script:
    - yarn --version
    - yarn run production --progress false
  artifacts:
    paths:
      - public/css/
      - public/js/
      - public/fonts/
      - public/mix-manifest.json
    expire_in: 1 days
    when: always

db-seeding:
  stage: building
  services:
    - {name: 'abkrim/mysql8_legacy_password:latest', alias: 'mysql'}
#    - mysql:latest
  image: edbizarro/gitlab-ci-pipeline-php:7.2
  dependencies:
    - composer
    - yarn
  script:
    - php artisan migrate:fresh --seed
  artifacts:
    paths:
      - ./storage/logs # for debugging
    expire_in: 1 days
    when: on_failure

phpunit:
  stage: testing
  services:
    - {name: 'abkrim/mysql8_legacy_password:latest', alias: 'mysql'}
#    - mysql:latest
  image: edbizarro/gitlab-ci-pipeline-php:7.2
  dependencies:
    - build-assets
    - composer
    - db-seeding
  script:
    - php -v
    - sudo cp /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.bak
    - echo "" | sudo tee /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    - find . -type f -name phpunit
    - ./vendor/phpunit/phpunit/phpunit --version
    - php -d short_open_tag=off ./vendor/phpunit/phpunit/phpunit -v --colors=never --stderr
    - sudo cp /usr/local/etc/php/conf.d/docker-php-ext-xdebug.bak /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  artifacts:
    paths:
      - ./storage/logs # for debugging
    expire_in: 1 days
    when: on_failure

codestyle:
  stage: testing
  image: lorisleiva/laravel-docker:latest
  script:
    - phpcs --standard=PSR2 --extensions=php app
  dependencies: []

phpcpd:
  stage: testing
  image: edbizarro/gitlab-ci-pipeline-php:7.2
  script:
    - test -f phpcpd.phar || curl -L https://phar.phpunit.de/phpcpd.phar -o phpcpd.phar
    - php phpcpd.phar app/ --min-lines=50
  dependencies: []
  cache:
    paths:
      - phpcpd.phar

sensiolabs:
  stage: security
  image: edbizarro/gitlab-ci-pipeline-php:7.2
  script:
    - test -d security-checker || git clone https://github.com/sensiolabs/security-checker.git
    - cd security-checker
    - composer install
    - php security-checker security:check ../composer.lock
  dependencies: []
  cache:
    paths:
      - security-checker/
```

Also tried purge all docker system and images

All tiemes same issue
