### ISSUE TITLE
[php:5.6] PDOException with message could not find driver mysql

### ISSUE THREAD

**Issue by fezfez** [edbizarro/gitlab-ci-pipeline-php#8]
.gitlab-ci.yml

```yml
before_script:
- composer -v
- composer install
- mkdir -p data/cache
- COMPOSER_PROCESS_TIMEOUT=0

stages:
  - test

cache:
  key: $CI_COMMIT_REF_NAME
  paths:
    - vendor
    - ~/.composer/cache/files
    
variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: homestead
  MYSQL_PASSWORD: secret
  MYSQL_DATABASE: homestead
  DB_HOST: mysql

test:5.6:
  stage: test
  image: edbizarro/gitlab-ci-pipeline-php:5.6
  services:
    - mysql:5.7
  script:
      - ./vendor/bin/phpunit

coverage:7.1:
  stage: test
  image: edbizarro/gitlab-ci-pipeline-php:7.1
  services:
    - mysql:5.7
  script:
    - phpdbg -qrr ./vendor/phpunit/phpunit/phpunit --coverage-text **--colors=never**
```

Output for test:5.6 job

```
Fatal error: Uncaught exception 'PDOException' with message 'could not find driver' in .../vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 115
```

The coverage:7.1 job is ok.

The error happen since a week, did you remove intentionally the pdo_mysql driver ?

Thanks in advance
