### ISSUE TITLE
PHPUnit\Framework\Exception: Module 'SimpleXML' already loaded

### ISSUE THREAD

**Issue by Cyrille37** [edbizarro/gitlab-ci-pipeline-php#9]
Hi,
I use this image on gitlab-ci (pipeline at gitlab.com) but since few times it failed running PhpUnit with error:

```
PHPUnit\Framework\Exception: PHP Warning:  Module 'SimpleXML' already loaded in Unknown on line 0
PHP Warning:  Module 'tokenizer' already loaded in Unknown on line 0
PHP Warning:  Module 'xmlwriter' already loaded in Unknown on line 0
```

My .gitlab-ci.yml is very simple:
```
cache:
  key: $CI_BUILD_REF_NAME
  paths:
    - vendor
    - ~/.composer/cache/files

before_script:

test:
  only:
    - schedules
  image: edbizarro/gitlab-ci-pipeline-php:7.1-alpine
  script:
    - composer install --no-interaction --no-progress
    - ./phpunit --colors --no-coverage --configuration phpunit.xml
```

Any idea ?
