### ISSUE TITLE
could not lock config file /root/.gitconfig: Operation not permitted

### ISSUE THREAD

**Issue by alex1702** [edbizarro/gitlab-ci-pipeline-php#98]
I get the following error message:
could not lock config file /root/.gitconfig: Operation not permitted

gitlab-ci.yml:
```yaml
stages:
  - prod

deploy2prod:
  stage: prod
  environment: production
  image: edbizarro/gitlab-ci-pipeline-php:7.3-alpine
  script:
    - sudo /my/private/path/deploy.sh
  only:
    - master
  tags:
    - srv01
```

Gitlab Output:
```
Running with gitlab-runner 13.2.2 (fedcba)
  on srv01-Docker-Runner abcdef
Preparing the "docker" executor
Using Docker executor with image edbizarro/gitlab-ci-pipeline-php:7.3-alpine ...
Pulling docker image edbizarro/gitlab-ci-pipeline-php:7.3-alpine ...
Using docker image sha256:66ddd6436954c6d91b9e48a90bcbb5297afdb9ee4fd73a0068ea2e444b846fcf for edbizarro/gitlab-ci-pipeline-php:7.3-alpine ...
Preparing environment
00:05
Running on runner-abcdef-project-117-concurrent-0 via srv01...
Getting source from Git repository
00:02
error: could not lock config file /root/.gitconfig: Operation not permitted
ERROR: Job failed: exit code 1
```

Gitlab raw Output:
```bash
[0KRunning with gitlab-runner 13.2.2 (a998cacd)
[0;m[0K  on srv01-Docker-Runner abcdef
[0;msection_start:1597038575:prepare_executor
[0K[0K[36;1mPreparing the "docker" executor[0;m
[0;m[0KUsing Docker executor with image edbizarro/gitlab-ci-pipeline-php:7.3-alpine ...
[0;m[0KPulling docker image edbizarro/gitlab-ci-pipeline-php:7.3-alpine ...
[0;m[0KUsing docker image sha256:1a95806f1ce5c3bd21e0fcd2a36a45b76030e67eff418c7e3da5d27a3e454f87 for edbizarro/gitlab-ci-pipeline-php:7.3-alpine ...
[0;msection_end:1597038594:prepare_executor
[0Ksection_start:1597038594:prepare_script
[0K[0K[36;1mPreparing environment[0;m
[0;mRunning on runner-abcdef-project-117-concurrent-0 via srv01...
section_end:1597038595:prepare_script
[0Ksection_start:1597038595:get_sources
[0K[0K[36;1mGetting source from Git repository[0;m
[0;merror: could not lock config file /root/.gitconfig: Operation not permitted
section_end:1597038597:get_sources
[0K[31;1mERROR: Job failed: exit code 1
[0;m
```
